/**
 * The mummy, rendered from a baked sprite sheet (generated by the standalone
 * SpriteGenerator sub-project from a parametric 3D model). Replaces the old
 * hand-drawn inline-SVG mummy. The sheet has 8 baked facings so the mummy really
 * turns toward the player (no L/R mirror trick), and an 8-frame walk cycle.
 *
 * Sheet layout (see mummy.meta.json): 64px frames, 8 columns (walk frames),
 * 16 rows — an idle block (rows 0-7, one per facing) then a walk block
 * (rows 8-15). We only use the WALK block on the board: walk frame 0 is a clean
 * neutral stand (both legs at phase 0), so it doubles as the resting pose, and a
 * hop plays frames 0-7 (driven imperatively by Board via the forwarded ref).
 */
import { forwardRef, useEffect, useRef } from 'react';
import type { CSSProperties } from 'react';
import type { MonsterKind, Pos } from '../../engine';
import meta from '../../assets/sprites/mummy.meta.json';
import whiteUrl from '../../assets/sprites/mummy_white.png';
import redUrl from '../../assets/sprites/mummy_red.png';

export type Facing8 = 'N' | 'NE' | 'E' | 'SE' | 'S' | 'SW' | 'W' | 'NW';
export type MummyVariant = 'white' | 'red';

export const MUMMY_FACINGS = meta.facings as Facing8[];
export const MUMMY_COLS = meta.columns;
export const MUMMY_ROWS = meta.rows;
const WALK = meta.clips.find((c) => c.name === 'walk')!;
export const MUMMY_WALK_ROW = WALK.row;
export const MUMMY_WALK_FRAMES = WALK.frames;
const HEADTURN = meta.clips.find((c) => c.name === 'headturn')!;
export const MUMMY_HEADTURN_ROW = HEADTURN.row;
export const MUMMY_HEADTURN_FRAMES = HEADTURN.frames;

const SHEET_URL: Record<MummyVariant, string> = { white: whiteUrl, red: redUrl };

export function isMummyKind(kind: MonsterKind): boolean {
  return kind.startsWith('mummy');
}
export function mummyVariant(kind: MonsterKind): MummyVariant {
  return kind.endsWith('red') ? 'red' : 'white';
}

/**
 * CARDINAL facing from `from` toward `to` (screen +y = South), by the dominant
 * axis. Only 90° turns — the mummy faces N/E/S/W, never a diagonal.
 */
export function mummyFacing(from: Pos, to: Pos): Facing8 {
  const dx = to.x - from.x;
  const dy = to.y - from.y;
  if (dx === 0 && dy === 0) return 'S';
  if (Math.abs(dx) >= Math.abs(dy)) return dx > 0 ? 'E' : 'W';
  return dy > 0 ? 'S' : 'N';
}

/**
 * Facing from an actual STEP (prev → cur): the mummy looks the way it walks.
 * Returns null when it didn't move (so the caller keeps the last facing until it
 * steps again — orientation only changes with movement). A single step is one
 * axis, so this is exact.
 */
export function moveFacing(prev: Pos, cur: Pos): Facing8 | null {
  const dx = cur.x - prev.x;
  const dy = cur.y - prev.y;
  if (dx === 0 && dy === 0) return null;
  if (Math.abs(dx) >= Math.abs(dy)) return dx > 0 ? 'E' : 'W';
  return dy > 0 ? 'S' : 'N';
}

/** The walk-block row index for a facing (used by Board to bake the hop keyframes). */
export function mummyWalkRow(facing: Facing8): number {
  return MUMMY_WALK_ROW + MUMMY_FACINGS.indexOf(facing);
}
function headTurnRow(facing: Facing8): number {
  return MUMMY_HEADTURN_ROW + MUMMY_FACINGS.indexOf(facing);
}

/** Background style showing one (row, frame) cell of the sheet at `size` px. */
function cellStyle(variant: MummyVariant, row: number, frame: number, size: number): CSSProperties {
  return {
    width: size,
    height: size,
    backgroundImage: `url(${SHEET_URL[variant]})`,
    backgroundRepeat: 'no-repeat',
    backgroundSize: `${MUMMY_COLS * size}px ${MUMMY_ROWS * size}px`,
    backgroundPosition: `${-frame * size}px ${-row * size}px`,
  };
}

/** Walk frame 0 (a clean stand) for `facing` — the resting/board pose. */
export function mummyCellStyle(variant: MummyVariant, facing: Facing8, size: number): CSSProperties {
  return cellStyle(variant, mummyWalkRow(facing), 0, size);
}

interface Props {
  variant: MummyVariant;
  facing: Facing8;
  size: number;
}

/** Forwards its ref to the background span so Board can animate the walk cycle. */
export const MummySheet = forwardRef<HTMLSpanElement, Props>(function MummySheet(
  { variant, facing, size },
  ref,
) {
  return <span ref={ref} className="mummy-sheet" style={mummyCellStyle(variant, facing, size)} />;
});

/**
 * The spawn head-twist: plays the baked head-turn clip once (frames 0→N over
 * `durationMs`, holding the last frame), body still, head spinning a full 360°.
 * Drawn from the same sheet/model as the settled mummy, so there is no pop when
 * the intro hands off to the normal sprite. rAF-driven; no React re-render.
 */
export function SpawnMummyHeadTurn({
  variant,
  facing,
  size,
  durationMs = 760,
}: Props & { durationMs?: number }) {
  const ref = useRef<HTMLSpanElement>(null);
  const row = headTurnRow(facing);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const N = MUMMY_HEADTURN_FRAMES;
    let raf = 0;
    let t0 = 0;
    const tick = (ts: number) => {
      if (!t0) t0 = ts;
      const t = Math.min(1, (ts - t0) / durationMs);
      const frame = Math.min(N - 1, Math.floor(t * N));
      el.style.backgroundPositionX = `${-frame * size}px`;
      if (t < 1) raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [row, size, durationMs]);
  return <span ref={ref} className="mummy-sheet" style={cellStyle(variant, row, 0, size)} />;
}
