/**
 * Level registry. AUTO-GENERATED by scripts/generate-levels.mjs — do not edit by
 * hand; re-run the generator (generate / extend) to change the pack.
 * Every level here is verified solvable by the exact BFS solver at build time,
 * and solvable WITHOUT any monster merge (forbidCollisions), so the collision
 * trick is never required.
 */
import { loadLevel, type Level, type LevelSpec } from '../engine';
import lvl_01_first_steps from './01-first-steps.json';
import lvl_02_slow_pursuit from './02-slow-pursuit.json';
import lvl_03_first_mummy from './03-first-mummy.json';
import lvl_04_the_long_wall from './04-the-long-wall.json';
import lvl_05_two_hunters from './05-two-hunters.json';
import lvl_06_trap_room from './06-trap-room.json';
import lvl_07_double_trouble from './07-double-trouble.json';
import lvl_08_locked_gate from './08-locked-gate.json';
import lvl_09_three_hunters from './09-three-hunters.json';
import lvl_10_the_gauntlet from './10-the-gauntlet.json';
import lvl_11_onslaught from './11-onslaught.json';
import lvl_12_final_trial from './12-final-trial.json';

const SPECS: LevelSpec[] = [
  lvl_01_first_steps as LevelSpec,
  lvl_02_slow_pursuit as LevelSpec,
  lvl_03_first_mummy as LevelSpec,
  lvl_04_the_long_wall as LevelSpec,
  lvl_05_two_hunters as LevelSpec,
  lvl_06_trap_room as LevelSpec,
  lvl_07_double_trouble as LevelSpec,
  lvl_08_locked_gate as LevelSpec,
  lvl_09_three_hunters as LevelSpec,
  lvl_10_the_gauntlet as LevelSpec,
  lvl_11_onslaught as LevelSpec,
  lvl_12_final_trial as LevelSpec,
];

/** Validated, runtime-ready levels in play order. */
export const LEVELS: Level[] = SPECS.map(loadLevel);

export function getLevel(id: string): Level | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function getLevelIndex(id: string): number {
  return LEVELS.findIndex((l) => l.id === id);
}

export function nextLevelId(id: string): string | undefined {
  const i = getLevelIndex(id);
  return i >= 0 && i < LEVELS.length - 1 ? LEVELS[i + 1].id : undefined;
}
