/**
 * Level registry. AUTO-GENERATED by scripts/generate-levels.mjs — do not edit by
 * hand; re-run the generator (generate / extend) to change the pack.
 * Every level here is verified at build time to be solvable by the exact BFS
 * solver AND to pass the curriculum quality filters: the naive "beeline" player
 * loses (levels >= #3), the nearest enemy starts close, and par exceeds the
 * straight-line distance. Levels 1-6 are additionally solvable WITHOUT any
 * monster merge; from level 7 a merge may be part of the intended solution.
 */
import { loadLevel, type Level, type LevelSpec } from '../engine';
import lvl_01_the_chase from './01-the-chase.json';
import lvl_02_broken_line from './02-broken-line.json';
import lvl_03_spikes from './03-spikes.json';
import lvl_04_the_other_way from './04-the-other-way.json';
import lvl_05_red_corridor from './05-red-corridor.json';
import lvl_06_two_hunters from './06-two-hunters.json';
import lvl_07_collision from './07-collision.json';
import lvl_08_scavenger from './08-scavenger.json';
import lvl_09_lock_key from './09-lock-key.json';
import lvl_10_ambush from './10-ambush.json';
import lvl_11_the_warren from './11-the-warren.json';
import lvl_12_final_trial from './12-final-trial.json';
import lvl_13_trial_13 from './13-trial-13.json';
import lvl_14_trial_14 from './14-trial-14.json';
import lvl_15_trial_15 from './15-trial-15.json';
import lvl_16_trial_16 from './16-trial-16.json';
import lvl_17_trial_17 from './17-trial-17.json';
import lvl_18_trial_18 from './18-trial-18.json';
import lvl_19_trial_19 from './19-trial-19.json';
import lvl_20_trial_20 from './20-trial-20.json';
import lvl_21_trial_21 from './21-trial-21.json';
import lvl_22_trial_22 from './22-trial-22.json';
import lvl_23_trial_23 from './23-trial-23.json';
import lvl_24_trial_24 from './24-trial-24.json';
import lvl_25_trial_25 from './25-trial-25.json';
import lvl_26_trial_26 from './26-trial-26.json';
import lvl_27_trial_27 from './27-trial-27.json';
import lvl_28_trial_28 from './28-trial-28.json';
import lvl_29_trial_29 from './29-trial-29.json';
import lvl_30_trial_30 from './30-trial-30.json';
import lvl_31_trial_31 from './31-trial-31.json';
import lvl_32_trial_32 from './32-trial-32.json';
import lvl_33_trial_33 from './33-trial-33.json';
import lvl_34_trial_34 from './34-trial-34.json';
import lvl_35_trial_35 from './35-trial-35.json';
import lvl_36_trial_36 from './36-trial-36.json';
import lvl_37_trial_37 from './37-trial-37.json';
import lvl_38_trial_38 from './38-trial-38.json';
import lvl_39_trial_39 from './39-trial-39.json';
import lvl_40_trial_40 from './40-trial-40.json';
import lvl_41_trial_41 from './41-trial-41.json';
import lvl_42_trial_42 from './42-trial-42.json';
import lvl_43_trial_43 from './43-trial-43.json';
import lvl_44_trial_44 from './44-trial-44.json';
import lvl_45_trial_45 from './45-trial-45.json';
import lvl_46_trial_46 from './46-trial-46.json';
import lvl_47_trial_47 from './47-trial-47.json';
import lvl_48_trial_48 from './48-trial-48.json';
import lvl_49_trial_49 from './49-trial-49.json';
import lvl_50_trial_50 from './50-trial-50.json';
import lvl_51_trial_51 from './51-trial-51.json';
import lvl_52_trial_52 from './52-trial-52.json';
import lvl_53_trial_53 from './53-trial-53.json';
import lvl_54_trial_54 from './54-trial-54.json';
import lvl_55_trial_55 from './55-trial-55.json';
import lvl_56_trial_56 from './56-trial-56.json';
import lvl_57_trial_57 from './57-trial-57.json';
import lvl_58_trial_58 from './58-trial-58.json';
import lvl_59_trial_59 from './59-trial-59.json';
import lvl_60_trial_60 from './60-trial-60.json';
import lvl_61_trial_61 from './61-trial-61.json';
import lvl_62_trial_62 from './62-trial-62.json';
import lvl_63_trial_63 from './63-trial-63.json';
import lvl_64_trial_64 from './64-trial-64.json';
import lvl_65_trial_65 from './65-trial-65.json';
import lvl_66_trial_66 from './66-trial-66.json';
import lvl_67_trial_67 from './67-trial-67.json';
import lvl_68_trial_68 from './68-trial-68.json';
import lvl_69_trial_69 from './69-trial-69.json';
import lvl_70_trial_70 from './70-trial-70.json';
import lvl_71_trial_71 from './71-trial-71.json';
import lvl_72_trial_72 from './72-trial-72.json';
import lvl_73_trial_73 from './73-trial-73.json';
import lvl_74_trial_74 from './74-trial-74.json';
import lvl_75_trial_75 from './75-trial-75.json';
import lvl_76_trial_76 from './76-trial-76.json';
import lvl_77_trial_77 from './77-trial-77.json';
import lvl_78_trial_78 from './78-trial-78.json';
import lvl_79_trial_79 from './79-trial-79.json';
import lvl_80_trial_80 from './80-trial-80.json';
import lvl_81_trial_81 from './81-trial-81.json';
import lvl_82_trial_82 from './82-trial-82.json';
import lvl_83_trial_83 from './83-trial-83.json';
import lvl_84_trial_84 from './84-trial-84.json';
import lvl_85_trial_85 from './85-trial-85.json';
import lvl_86_trial_86 from './86-trial-86.json';
import lvl_87_trial_87 from './87-trial-87.json';
import lvl_88_trial_88 from './88-trial-88.json';
import lvl_89_trial_89 from './89-trial-89.json';
import lvl_90_trial_90 from './90-trial-90.json';
import lvl_91_trial_91 from './91-trial-91.json';
import lvl_92_trial_92 from './92-trial-92.json';
import lvl_93_trial_93 from './93-trial-93.json';
import lvl_94_trial_94 from './94-trial-94.json';
import lvl_95_trial_95 from './95-trial-95.json';
import lvl_96_trial_96 from './96-trial-96.json';
import lvl_97_trial_97 from './97-trial-97.json';
import lvl_98_trial_98 from './98-trial-98.json';
import lvl_99_trial_99 from './99-trial-99.json';
import lvl_100_trial_100 from './100-trial-100.json';
import lvl_101_trial_101 from './101-trial-101.json';
import lvl_102_trial_102 from './102-trial-102.json';
import lvl_103_trial_103 from './103-trial-103.json';
import lvl_104_trial_104 from './104-trial-104.json';
import lvl_105_trial_105 from './105-trial-105.json';
import lvl_106_trial_106 from './106-trial-106.json';
import lvl_107_trial_107 from './107-trial-107.json';
import lvl_108_trial_108 from './108-trial-108.json';
import lvl_109_trial_109 from './109-trial-109.json';
import lvl_110_trial_110 from './110-trial-110.json';
import lvl_111_trial_111 from './111-trial-111.json';
import lvl_112_trial_112 from './112-trial-112.json';
import lvl_113_trial_113 from './113-trial-113.json';
import lvl_114_trial_114 from './114-trial-114.json';
import lvl_115_trial_115 from './115-trial-115.json';
import lvl_116_trial_116 from './116-trial-116.json';
import lvl_117_trial_117 from './117-trial-117.json';
import lvl_118_trial_118 from './118-trial-118.json';
import lvl_119_trial_119 from './119-trial-119.json';
import lvl_120_trial_120 from './120-trial-120.json';
import lvl_121_trial_121 from './121-trial-121.json';
import lvl_122_trial_122 from './122-trial-122.json';
import lvl_123_trial_123 from './123-trial-123.json';
import lvl_124_trial_124 from './124-trial-124.json';
import lvl_125_trial_125 from './125-trial-125.json';
import lvl_126_trial_126 from './126-trial-126.json';
import lvl_127_trial_127 from './127-trial-127.json';
import lvl_128_trial_128 from './128-trial-128.json';
import lvl_129_trial_129 from './129-trial-129.json';
import lvl_130_trial_130 from './130-trial-130.json';
import lvl_131_trial_131 from './131-trial-131.json';
import lvl_132_trial_132 from './132-trial-132.json';
import lvl_133_trial_133 from './133-trial-133.json';
import lvl_134_trial_134 from './134-trial-134.json';
import lvl_135_trial_135 from './135-trial-135.json';
import lvl_136_trial_136 from './136-trial-136.json';
import lvl_137_trial_137 from './137-trial-137.json';
import lvl_138_trial_138 from './138-trial-138.json';
import lvl_139_trial_139 from './139-trial-139.json';
import lvl_140_trial_140 from './140-trial-140.json';
import lvl_141_trial_141 from './141-trial-141.json';
import lvl_142_trial_142 from './142-trial-142.json';
import lvl_143_trial_143 from './143-trial-143.json';
import lvl_144_trial_144 from './144-trial-144.json';
import lvl_145_trial_145 from './145-trial-145.json';
import lvl_146_trial_146 from './146-trial-146.json';
import lvl_147_trial_147 from './147-trial-147.json';
import lvl_148_trial_148 from './148-trial-148.json';
import lvl_149_trial_149 from './149-trial-149.json';
import lvl_150_trial_150 from './150-trial-150.json';
import lvl_151_trial_151 from './151-trial-151.json';
import lvl_152_trial_152 from './152-trial-152.json';
import lvl_153_trial_153 from './153-trial-153.json';
import lvl_154_trial_154 from './154-trial-154.json';
import lvl_155_trial_155 from './155-trial-155.json';
import lvl_156_trial_156 from './156-trial-156.json';
import lvl_157_trial_157 from './157-trial-157.json';
import lvl_158_trial_158 from './158-trial-158.json';
import lvl_159_trial_159 from './159-trial-159.json';
import lvl_160_trial_160 from './160-trial-160.json';
import lvl_161_trial_161 from './161-trial-161.json';
import lvl_162_trial_162 from './162-trial-162.json';
import lvl_163_trial_163 from './163-trial-163.json';
import lvl_164_trial_164 from './164-trial-164.json';
import lvl_165_trial_165 from './165-trial-165.json';
import lvl_166_trial_166 from './166-trial-166.json';
import lvl_167_trial_167 from './167-trial-167.json';
import lvl_168_trial_168 from './168-trial-168.json';
import lvl_169_trial_169 from './169-trial-169.json';
import lvl_170_trial_170 from './170-trial-170.json';

const SPECS: LevelSpec[] = [
  lvl_01_the_chase as LevelSpec,
  lvl_02_broken_line as LevelSpec,
  lvl_03_spikes as LevelSpec,
  lvl_04_the_other_way as LevelSpec,
  lvl_05_red_corridor as LevelSpec,
  lvl_06_two_hunters as LevelSpec,
  lvl_07_collision as LevelSpec,
  lvl_08_scavenger as LevelSpec,
  lvl_09_lock_key as LevelSpec,
  lvl_10_ambush as LevelSpec,
  lvl_11_the_warren as LevelSpec,
  lvl_12_final_trial as LevelSpec,
  lvl_13_trial_13 as LevelSpec,
  lvl_14_trial_14 as LevelSpec,
  lvl_15_trial_15 as LevelSpec,
  lvl_16_trial_16 as LevelSpec,
  lvl_17_trial_17 as LevelSpec,
  lvl_18_trial_18 as LevelSpec,
  lvl_19_trial_19 as LevelSpec,
  lvl_20_trial_20 as LevelSpec,
  lvl_21_trial_21 as LevelSpec,
  lvl_22_trial_22 as LevelSpec,
  lvl_23_trial_23 as LevelSpec,
  lvl_24_trial_24 as LevelSpec,
  lvl_25_trial_25 as LevelSpec,
  lvl_26_trial_26 as LevelSpec,
  lvl_27_trial_27 as LevelSpec,
  lvl_28_trial_28 as LevelSpec,
  lvl_29_trial_29 as LevelSpec,
  lvl_30_trial_30 as LevelSpec,
  lvl_31_trial_31 as LevelSpec,
  lvl_32_trial_32 as LevelSpec,
  lvl_33_trial_33 as LevelSpec,
  lvl_34_trial_34 as LevelSpec,
  lvl_35_trial_35 as LevelSpec,
  lvl_36_trial_36 as LevelSpec,
  lvl_37_trial_37 as LevelSpec,
  lvl_38_trial_38 as LevelSpec,
  lvl_39_trial_39 as LevelSpec,
  lvl_40_trial_40 as LevelSpec,
  lvl_41_trial_41 as LevelSpec,
  lvl_42_trial_42 as LevelSpec,
  lvl_43_trial_43 as LevelSpec,
  lvl_44_trial_44 as LevelSpec,
  lvl_45_trial_45 as LevelSpec,
  lvl_46_trial_46 as LevelSpec,
  lvl_47_trial_47 as LevelSpec,
  lvl_48_trial_48 as LevelSpec,
  lvl_49_trial_49 as LevelSpec,
  lvl_50_trial_50 as LevelSpec,
  lvl_51_trial_51 as LevelSpec,
  lvl_52_trial_52 as LevelSpec,
  lvl_53_trial_53 as LevelSpec,
  lvl_54_trial_54 as LevelSpec,
  lvl_55_trial_55 as LevelSpec,
  lvl_56_trial_56 as LevelSpec,
  lvl_57_trial_57 as LevelSpec,
  lvl_58_trial_58 as LevelSpec,
  lvl_59_trial_59 as LevelSpec,
  lvl_60_trial_60 as LevelSpec,
  lvl_61_trial_61 as LevelSpec,
  lvl_62_trial_62 as LevelSpec,
  lvl_63_trial_63 as LevelSpec,
  lvl_64_trial_64 as LevelSpec,
  lvl_65_trial_65 as LevelSpec,
  lvl_66_trial_66 as LevelSpec,
  lvl_67_trial_67 as LevelSpec,
  lvl_68_trial_68 as LevelSpec,
  lvl_69_trial_69 as LevelSpec,
  lvl_70_trial_70 as LevelSpec,
  lvl_71_trial_71 as LevelSpec,
  lvl_72_trial_72 as LevelSpec,
  lvl_73_trial_73 as LevelSpec,
  lvl_74_trial_74 as LevelSpec,
  lvl_75_trial_75 as LevelSpec,
  lvl_76_trial_76 as LevelSpec,
  lvl_77_trial_77 as LevelSpec,
  lvl_78_trial_78 as LevelSpec,
  lvl_79_trial_79 as LevelSpec,
  lvl_80_trial_80 as LevelSpec,
  lvl_81_trial_81 as LevelSpec,
  lvl_82_trial_82 as LevelSpec,
  lvl_83_trial_83 as LevelSpec,
  lvl_84_trial_84 as LevelSpec,
  lvl_85_trial_85 as LevelSpec,
  lvl_86_trial_86 as LevelSpec,
  lvl_87_trial_87 as LevelSpec,
  lvl_88_trial_88 as LevelSpec,
  lvl_89_trial_89 as LevelSpec,
  lvl_90_trial_90 as LevelSpec,
  lvl_91_trial_91 as LevelSpec,
  lvl_92_trial_92 as LevelSpec,
  lvl_93_trial_93 as LevelSpec,
  lvl_94_trial_94 as LevelSpec,
  lvl_95_trial_95 as LevelSpec,
  lvl_96_trial_96 as LevelSpec,
  lvl_97_trial_97 as LevelSpec,
  lvl_98_trial_98 as LevelSpec,
  lvl_99_trial_99 as LevelSpec,
  lvl_100_trial_100 as LevelSpec,
  lvl_101_trial_101 as LevelSpec,
  lvl_102_trial_102 as LevelSpec,
  lvl_103_trial_103 as LevelSpec,
  lvl_104_trial_104 as LevelSpec,
  lvl_105_trial_105 as LevelSpec,
  lvl_106_trial_106 as LevelSpec,
  lvl_107_trial_107 as LevelSpec,
  lvl_108_trial_108 as LevelSpec,
  lvl_109_trial_109 as LevelSpec,
  lvl_110_trial_110 as LevelSpec,
  lvl_111_trial_111 as LevelSpec,
  lvl_112_trial_112 as LevelSpec,
  lvl_113_trial_113 as LevelSpec,
  lvl_114_trial_114 as LevelSpec,
  lvl_115_trial_115 as LevelSpec,
  lvl_116_trial_116 as LevelSpec,
  lvl_117_trial_117 as LevelSpec,
  lvl_118_trial_118 as LevelSpec,
  lvl_119_trial_119 as LevelSpec,
  lvl_120_trial_120 as LevelSpec,
  lvl_121_trial_121 as LevelSpec,
  lvl_122_trial_122 as LevelSpec,
  lvl_123_trial_123 as LevelSpec,
  lvl_124_trial_124 as LevelSpec,
  lvl_125_trial_125 as LevelSpec,
  lvl_126_trial_126 as LevelSpec,
  lvl_127_trial_127 as LevelSpec,
  lvl_128_trial_128 as LevelSpec,
  lvl_129_trial_129 as LevelSpec,
  lvl_130_trial_130 as LevelSpec,
  lvl_131_trial_131 as LevelSpec,
  lvl_132_trial_132 as LevelSpec,
  lvl_133_trial_133 as LevelSpec,
  lvl_134_trial_134 as LevelSpec,
  lvl_135_trial_135 as LevelSpec,
  lvl_136_trial_136 as LevelSpec,
  lvl_137_trial_137 as LevelSpec,
  lvl_138_trial_138 as LevelSpec,
  lvl_139_trial_139 as LevelSpec,
  lvl_140_trial_140 as LevelSpec,
  lvl_141_trial_141 as LevelSpec,
  lvl_142_trial_142 as LevelSpec,
  lvl_143_trial_143 as LevelSpec,
  lvl_144_trial_144 as LevelSpec,
  lvl_145_trial_145 as LevelSpec,
  lvl_146_trial_146 as LevelSpec,
  lvl_147_trial_147 as LevelSpec,
  lvl_148_trial_148 as LevelSpec,
  lvl_149_trial_149 as LevelSpec,
  lvl_150_trial_150 as LevelSpec,
  lvl_151_trial_151 as LevelSpec,
  lvl_152_trial_152 as LevelSpec,
  lvl_153_trial_153 as LevelSpec,
  lvl_154_trial_154 as LevelSpec,
  lvl_155_trial_155 as LevelSpec,
  lvl_156_trial_156 as LevelSpec,
  lvl_157_trial_157 as LevelSpec,
  lvl_158_trial_158 as LevelSpec,
  lvl_159_trial_159 as LevelSpec,
  lvl_160_trial_160 as LevelSpec,
  lvl_161_trial_161 as LevelSpec,
  lvl_162_trial_162 as LevelSpec,
  lvl_163_trial_163 as LevelSpec,
  lvl_164_trial_164 as LevelSpec,
  lvl_165_trial_165 as LevelSpec,
  lvl_166_trial_166 as LevelSpec,
  lvl_167_trial_167 as LevelSpec,
  lvl_168_trial_168 as LevelSpec,
  lvl_169_trial_169 as LevelSpec,
  lvl_170_trial_170 as LevelSpec,
];

/** Validated, runtime-ready levels in play order. */
export const LEVELS: Level[] = SPECS.map(loadLevel);

export function getLevel(id: string): Level | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function getLevelIndex(id: string): number {
  return LEVELS.findIndex((l) => l.id === id);
}

export function nextLevelId(id: string): string | undefined {
  const i = getLevelIndex(id);
  return i >= 0 && i < LEVELS.length - 1 ? LEVELS[i + 1].id : undefined;
}
