/**
 * Level registry. AUTO-GENERATED by scripts/generate-levels.mjs — do not edit by
 * hand; re-run the generator (generate / extend) to change the pack.
 * Every level here is verified at build time to be solvable by the exact BFS
 * solver AND to pass the curriculum quality filters: the naive "beeline" player
 * loses (levels >= #3), the nearest enemy starts close, and par exceeds the
 * straight-line distance. Levels 1-6 are additionally solvable WITHOUT any
 * monster merge; from level 7 a merge may be part of the intended solution.
 */
import { loadLevel, type Level, type LevelSpec } from '../engine';
import lvl_01_the_chase from './01-the-chase.json';
import lvl_02_broken_line from './02-broken-line.json';
import lvl_03_spikes from './03-spikes.json';
import lvl_04_the_other_way from './04-the-other-way.json';
import lvl_05_red_corridor from './05-red-corridor.json';
import lvl_06_two_hunters from './06-two-hunters.json';
import lvl_07_collision from './07-collision.json';
import lvl_08_scavenger from './08-scavenger.json';
import lvl_09_lock_key from './09-lock-key.json';
import lvl_10_ambush from './10-ambush.json';
import lvl_11_the_warren from './11-the-warren.json';
import lvl_12_final_trial from './12-final-trial.json';
import lvl_13_trial_13 from './13-trial-13.json';
import lvl_14_trial_14 from './14-trial-14.json';
import lvl_15_trial_15 from './15-trial-15.json';
import lvl_16_trial_16 from './16-trial-16.json';
import lvl_17_trial_17 from './17-trial-17.json';
import lvl_18_trial_18 from './18-trial-18.json';
import lvl_19_trial_19 from './19-trial-19.json';
import lvl_20_trial_20 from './20-trial-20.json';

const SPECS: LevelSpec[] = [
  lvl_01_the_chase as LevelSpec,
  lvl_02_broken_line as LevelSpec,
  lvl_03_spikes as LevelSpec,
  lvl_04_the_other_way as LevelSpec,
  lvl_05_red_corridor as LevelSpec,
  lvl_06_two_hunters as LevelSpec,
  lvl_07_collision as LevelSpec,
  lvl_08_scavenger as LevelSpec,
  lvl_09_lock_key as LevelSpec,
  lvl_10_ambush as LevelSpec,
  lvl_11_the_warren as LevelSpec,
  lvl_12_final_trial as LevelSpec,
  lvl_13_trial_13 as LevelSpec,
  lvl_14_trial_14 as LevelSpec,
  lvl_15_trial_15 as LevelSpec,
  lvl_16_trial_16 as LevelSpec,
  lvl_17_trial_17 as LevelSpec,
  lvl_18_trial_18 as LevelSpec,
  lvl_19_trial_19 as LevelSpec,
  lvl_20_trial_20 as LevelSpec,
];

/** Validated, runtime-ready levels in play order. */
export const LEVELS: Level[] = SPECS.map(loadLevel);

export function getLevel(id: string): Level | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function getLevelIndex(id: string): number {
  return LEVELS.findIndex((l) => l.id === id);
}

export function nextLevelId(id: string): string | undefined {
  const i = getLevelIndex(id);
  return i >= 0 && i < LEVELS.length - 1 ? LEVELS[i + 1].id : undefined;
}
